# This workflow builds and tests the .NET project.
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Core Desktop CI/CD

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on. WPF requires a Windows environment.
    runs-on: windows-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout repository
      uses: actions/checkout@v4

    # Sets up the specified version of the .NET SDK
    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    # Restores the dependencies and tools of the project
    - name: Restore Dependencies
      run: dotnet restore

    # Builds the project and all of its dependencies
    - name: Build Project
      run: dotnet build --configuration Release --no-restore

    # Runs the unit tests for the solution
    - name: Run Tests
      run: dotnet test --configuration Release --no-build --verbosity normal
